# LanceDB Fundamental

In [1]:
import lancedb
from constants import KNOWLEDGE_BASE_PATH

vector_db = lancedb.connect(KNOWLEDGE_BASE_PATH)
vector_db

LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base')

## Read the file

In [2]:
import json

with open("animals_text_embeddings.json") as file:
    data = json.load(file)

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

## Create a table from the data readed

In [3]:
vector_db.create_table("animal_text", exist_ok=True, data=data)
vector_db["animal_text"]

LanceTable(name='animal_text', version=1, _conn=LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base'))

## Convert the data in a dataframe with pandas

In [4]:
vector_db["animal_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

In [5]:
vector_db["animal_text"].head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

## For add more data

In [6]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]
more_data

[{'text': 'A panda eating bamboo peacefully.', 'vector': [0.51, 0.37, 0.82]},
 {'text': 'A lion roaring loudly on a rock.', 'vector': [0.93, 0.18, 0.41]}]

## for add those new data in the vectorDB

In [7]:
vector_db["animal_text"].add(more_data)

AddResult(version=2)

In [8]:
vector_db["animal_text"].to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Creata a empty table

In [9]:
from lancedb.pydantic import LanceModel

class Article(LanceModel):
    title: str
    content: str

vector_db.create_table("articles", schema=Article, exist_ok=True)

LanceTable(name='articles', version=1, _conn=LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base'))