# LanceDB Fundamental

In [27]:
import lancedb
from constants import KNOWLEDGE_BASE_PATH

vector_db = lancedb.connect(KNOWLEDGE_BASE_PATH)
vector_db

LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base')

## Read the file

In [28]:
import json

with open("animals_text_embeddings.json") as file:
    data = json.load(file)

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

## Create a table from the data readed

In [29]:
vector_db.create_table("animal_text", exist_ok=True, data=data)
vector_db["animal_text"]

LanceTable(name='animal_text', version=5, _conn=LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base'))

## Convert the data in a dataframe with pandas

In [30]:
vector_db["animal_text"].to_pandas()

                                             text              vector
0                      A small brown dog running.  [0.12, 0.85, 0.33]
1                A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2           A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3   A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4          A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                   A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
8               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
9                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
10              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
11               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
12              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
13               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [31]:
vector_db["animal_text"].head()

pyarrow.Table
text: string
vector: fixed_size_list<item: float>[3]
  child 0, item: float
----
text: [["A small brown dog running.","A cat resting quietly on a sofa.","A large gray elephant drinking water.","A fast cheetah sprinting across the savannah.","A colorful parrot perched on a branch."]]
vector: [[[0.12,0.85,0.33],[0.4,0.91,0.1],[0.88,0.22,0.55],[0.95,0.12,0.72],[0.25,0.66,0.81]]]

## For add more data

In [32]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]
more_data

[{'text': 'A panda eating bamboo peacefully.', 'vector': [0.51, 0.37, 0.82]},
 {'text': 'A lion roaring loudly on a rock.', 'vector': [0.93, 0.18, 0.41]}]

## for add those new data in the vectorDB

In [33]:
vector_db["animal_text"].add(more_data)

AddResult(version=6)

In [34]:
vector_db["animal_text"].to_pandas()

                                             text              vector
0                      A small brown dog running.  [0.12, 0.85, 0.33]
1                A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2           A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3   A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4          A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                   A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
8               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
9                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
10              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
11               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
12              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
13               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
14              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
15               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Creata a empty table

In [35]:
from lancedb.pydantic import LanceModel

class Article(LanceModel):
    title: str
    content: str

vector_db.create_table("articles", schema=Article, exist_ok=True)

LanceTable(name='articles', version=1, _conn=LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base'))

In [36]:
vector_db.list_tables()

ListTablesResponse(tables=['animal_text', 'articles', 'jokes'], page_token=None)

## TODO: Add data to article table

In [37]:
article_data = [{
    "title": "Fiskar",
    "content": """A fish is an aquatic, anamniotic, gill-bearing vertebrate animal with a tough
      cranium to protect the brain, but lacking limbs with digits. 
      Fish can be grouped into the more basal jawless fish and the more common jawed fish,
        the latter including all living cartilaginous and bony fish, 
        as well as the extinct placoderms and acanthodians.
     In a break from the long tradition of grouping all fish into a single class (Pisces),
     modern phylogenetics views fish as a paraphyletic group that includes all vertebrates except tetrapods.
     In English, the plural of "fish" is fish when referring to individuals and fishes when referring to species."""},
    {"title": "Crabs",
     
     "content": """Crabs are decapod crustaceans, either the Brachyura (the "true crabs")
       or various groups within the closely related Anomura 
       (hermit crabs and allies), characterised by having a heavily armoured shell,
         their tail segments concealed under the body, the ability to run sideways,
           and the habit of hiding in rocky crevices.
             They do not form a single natural group or clade,
     but have convergently evolved multiple times from the ancestral decapod body plan through carcinisation,
       the process of creating this set of characteristics.
     As a group, they are thus polyphyletic,
       meaning they have multiple evolutionary origins."""
     },
     ]
vector_db["articles"].add(article_data)

AddResult(version=2)

In [38]:
vector_db["articles"].to_pandas()

    title                                            content
0  Fiskar  A fish is an aquatic, anamniotic, gill-bearing...
1   Crabs  Crabs are decapod crustaceans, either the Brac...

## drop table :

In [39]:
vector_db.drop_table("articles")

In [40]:
vector_db.list_tables() # .table_names() for intel macs

ListTablesResponse(tables=['animal_text', 'jokes'], page_token=None)

## Vector search in LanceDb

Flow here:
1. use embedding model to create vector embedding for each document
2. use same embedding model to create vector embedding of the query
3. send in the query_vector to search for closest documents

If we want to do RAG -> send in closest document to LLM to use

In [41]:
vector_db["animal_text"].to_pandas()

                                             text              vector
0                      A small brown dog running.  [0.12, 0.85, 0.33]
1                A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2           A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3   A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4          A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                   A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
8               A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
9                A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
10              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
11               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
12              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
13               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]
14              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
15               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

In [42]:
query_vector = [0.5, 0.2, 0.9]
vector_db["animal_text"].search(query_vector).to_pandas()

                                            text              vector  _distance
0              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
1              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
2              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
3              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
4              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
5  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]     0.2413
6          A large gray elephant drinking water.  [0.88, 0.22, 0.55]     0.2673
7         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]     0.2822
8               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]     0.4254
9               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]     0.4254

In [43]:
query_vector = [0.5, 0.2, 0.9]
df = vector_db["animal_text"].search(query_vector).limit(3).to_pandas() # we can use to_list() if we whant
df

                                text              vector  _distance
0  A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
1  A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354
2  A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]     0.0354

## Use embeddings API for create by our self vectors:
- makes life simple 
- automatic generate embeddings

embeddings model free can be foud in cohere

In [44]:
from lancedb.embeddings import get_registry
from dotenv import load_dotenv
load_dotenv()

embedding_model = get_registry().get("cohere").create(name = "embed-multilingual-v3.0")

# how big is the vector column.
embedding_model.ndims()

1024

##

In [45]:
from lancedb.pydantic import Vector

class JokeModel(LanceModel):
    joke: str = embedding_model.SourceField()
    embedding: Vector(embedding_model.ndims()) = embedding_model.VectorField() # type:ignore

vector_db.create_table("jokes", schema=JokeModel, exist_ok=True)
vector_db["jokes"]

LanceTable(name='jokes', version=1, _conn=LanceDBConnection(uri='c:\\Users\\aless\\Documents\\llmops_alessandro_abbate_mlo25\\09_lancedb\\knowlwdge_base'))

In [46]:
import pandas as pd
with open("jokes.json", encoding="utf8") as file:
    jokes_data = json.load(file)

df_jokes = pd.DataFrame(jokes_data)
df_jokes.head()

                                                joke
0  Parallel lines have so much in common—it’s sad...
1  ETL stands for “Extract, Transform, Leave for ...
2  What do you call a snake that runs your script...
3  Gold walks into a bar. The bartender says, “Au...
4   C# devs don’t argue; they just throw exceptions.

## set those data in our tabell

In [47]:

vector_db["jokes"].add(df_jokes)

AddResult(version=2)

In [48]:
vector_db["jokes"].to_pandas()

                                                 joke                                          embedding
0   Parallel lines have so much in common—it’s sad...  [-0.0032196045, 0.0011167526, -0.014953613, 0....
1   ETL stands for “Extract, Transform, Leave for ...  [0.012634277, 0.005268097, -0.09136963, 0.0809...
2   What do you call a snake that runs your script...  [0.019165039, 0.044677734, -0.021530151, 0.028...
3   Gold walks into a bar. The bartender says, “Au...  [0.019866943, 0.05999756, 0.012702942, 0.02343...
4    C# devs don’t argue; they just throw exceptions.  [0.013122559, 0.002374649, -0.05706787, 0.0608...
5   I asked the data lake if it had my file. It sa...  [-0.025970459, 0.0035209656, -0.061584473, 0.0...
6         My math teacher said I’m average… how mean!  [-0.0026016235, 0.03112793, 0.013343811, 0.030...
7   Python is so friendly even whitespace gets a say.  [0.0146484375, 0.016906738, -0.0026435852, 0.0...
8   The C# compiler walked into a bar. The bartend...  [0.0038490295, 0.006790161, -0.0769043, 0.0265...
9        Never trust an atom—they make up everything.  [-0.008956909, 0.003440857, -0.020614624, 0.04...
10  Why was the equal sign so humble? It knew it w...  [0.017501831, 0.021377563, -0.012313843, 0.070...
11  My Python code works on the first try… said no...  [0.02017212, 0.035736084, -0.008163452, 0.0485...
12  Why did the chemist ground his kids? Because t...  [-0.008056641, 0.031555176, -0.019454956, 0.01...
13  Our data pipeline broke… but don't worry, it w...  [-0.009239197, -0.011238098, -0.046722412, 0.0...
14  C# programmers love coffee—they're always work...  [-0.00541687, 0.0017910004, -0.060943604, 0.03...
15    I told a chemistry joke… there was no reaction.  [-0.03274536, 0.018218994, 0.039276123, 0.0012...
16  Python devs never get lost—they always know th...  [0.017852783, 0.026443481, -0.03829956, 0.0384...
17  Data engineer motto: If it works, don’t touch ...  [0.040740967, 0.007030487, -0.046173096, 0.098...
18                Why’s 6 afraid of 7? Because 7 8 9.  [0.005886078, 0.020553589, -0.0031318665, 0.01...
19  I put “root beer” in a square glass… now it’s ...  [0.008476257, 0.026138306, 0.046020508, 0.0015...
20  Why do data engineers hate nature? Too many un...  [0.039031982, 0.06201172, -0.02418518, 0.05044...
21             Oxygen and Magnesium got together—OMg!  [-0.04119873, -0.004600525, 0.007701874, 0.006...
22  Why did the Python programmer get bitten? Beca...  [0.012016296, 0.057678223, -0.0284729, 0.01250...
23  I tried to explain async/await to my friend… n...  [0.0028648376, 0.007926941, -0.016326904, 0.00...
24  Chemists have all the solutions… mostly in bea...  [0.0013589859, 0.03086853, -0.0012874603, 0.02...
25  Dear algebra, please stop asking us to find yo...  [0.011245728, 0.0046691895, -0.018936157, 0.06...
26  My pipeline failed again, so I’m logging out—l...  [0.0029716492, 0.002773285, -0.0748291, 0.0682...
27  Why did the C# developer go broke? He kept usi...  [0.028945923, 0.03753662, -0.03363037, 0.07330...
28  Why is C# like a musical? It has so many classes.  [-0.019012451, -0.016098022, -0.049621582, 0.0...
29  Python devs don’t need therapy—they already im...  [-0.0014638901, 0.018875122, 0.0059280396, 0.0...